server:
  port: 8081
spring:
  application:
    name: flow
  datasource:
    url: jdbc:mysql://192.168.7.18:3306/flowable?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

flowable:
  async-executor-activate: false  # 关闭定时任务 job
  database-schema-update: true  # 将databaseSchemaUpdate 设置为 true。当 Flowable 发现库与数据表结构不一致时，会自动将数据库表结构升级至最新版本
#  process:
#    definition-cache-limit: 100  # 定义进程容量
