server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.7.18:3306/flowable-spring-boot?characterEncoding=UTF-8;useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

flowable:
  async-executor-activate: false
  database-schema-update: true
